### PR TITLE
A deep selection Zipper concept implementation.

### PR DESCRIPTION
**Pull request by ncreep**

### CODE REVIEW

**Comment by djspiewak** [comment]
Just FYI, I haven't forgotten about this!  I was on vacation until yesterday, but I did spend some time thinking about what you wrote.  For starters, the idea of a _separate_ deep zipper class is brilliant, and solves a lot of problems I couldn't get around.  I'm not too keen on the Time idea (seems messy and error prone), but I need to userstand the code more to say if we can do without it.  I'll be working on Anti-XML for basically two full days this weekend at the Scala hackathon, so I should get the review done during that.

**Comment by ncreep** [comment]
I don't like the Time idea too much either, but it helps conflict resolution when merging different versions of the same node.
I see it as a way to propagate the user's intent through the updates/merges. Another solution would be to keep a full blown "history" of the updates, but that seems way too complex.

**Comment by ncreep** [comment]
Messed up with the commit description, I'm a github newbie, sorry...

Anyways, DeepZipper is now fully functional and passes all the tests defined for Zipper, plus the tests I previously defined before implementing flatMap.
This also includes selection on non Node types.

Now I need to write some specialized tests for deep selection with flatMapping, especially checking how consecutive flatMaps affect the whole process.

**Comment by djspiewak** [comment]
Worry thee not about commit messages!  Of course, they're important documentation, but only _slightly_ more important than back-of-the-napkin notes.

**Pull request merged**
