### PR TITLE
Namespaces

### PR DESCRIPTION
**Pull request by jespersm**
That was pretty painless. Oh, blast, now it wants to merge into master, I wonder why that is.

### CODE REVIEW

**Comment by djspiewak** [comment]
I'll take a pass at this tonight.  Looks good at very first glance though.  Thanks for working on this!

> I also took the tests for escaped elements and attribute names out

Fair enough.  I'll open a separate issue to add proper identifier checking (to ensure that we don't have reserved chars in names).  At that point, we can restore the specs w.r.t. whatever exception we decide to throw.

**Comment by djspiewak** [comment]
Actually, I just thought of something.  Right now, `Elem` uses `QName` directly, which can get a little confusing when it comes time to pattern match:

``` scala
val elem = Elem("foo", Attributes(), Map(), Group())
elem match {
  case Elem("foo", _, _, _) =>    // won't compile!
}
```

There is a magic implicit from `String => QName`, but implicits don't work in pattern matching.  This isn't a problem for attributes (which is where the implicit was designed to be used) since attributes cannot be extracted in this way, but it is a little bit weird with `Elem` matching.  Considering that this is something people are going to be doing a lot, I wonder if it's worth thinking about it a touch.

I can think of two alternatives which would clean this up a bit:
- Implement an `ElemNs` deconstructor for pattern matching
- Make store the prefix and name in `Elem` directly, rather than delegating to `QName`

The first option is really ugly, and I think even less intuitive than having to always remember to match using `Elem(QName(`.  The second option appeals to me quite a bit.  It forces users to always be explicit about the prefix when creating an `Elem`, since the implicit isn't even an option.  The downside is that the qname itself is no longer reified in `Elem`.  Can you envision a case this would interrupt?  Am I freaking out over nothing here?

This won't affect whether or not I merge the commits; it's really more of a follow-up thought.

**Comment by jespersm** [comment]
Unrolling QName inside Elem makes sense.

The deconstructor NsElem is VERY useful, but for matching on the namespace URI instead.

**Comment by djspiewak** [comment]
> Unrolling QName inside Elem makes sense.

Alright, I'll take care of that then.

> The deconstructor NsElem is VERY useful, but for matching on the namespace URI instead.

Very logical indeed.  You've convinced me on this one.

**Comment by jespersm** [comment]
I'm also working on unrolling :-) You said you were doing issue #13...

**Comment by djspiewak** [comment]
Perfect!  I _am_ working on #13, I just didn't want to make you feel like you had to do _everything_.  Looking forward to the unrolling pull…

**Pull request merged**
