### PR TITLE
PathCreator Bloom filters

### PR DESCRIPTION
**Pull request by ncreep**
An initial attempt at adding Bloom filters to selection with PathCreator.

Not sure that this is the best approach, as now it is not evident from the Selector trait that you can participate in optimizations on Elem types.

### CODE REVIEW

**Comment by josharnold52** [comment]
Why the change to Selector?  I think you could make `dispatchSelector` work with the original version.   Restricting the filter optimization to Selectors that return Elements seems unnecessary.  

I do like the idea of adding a `matches(String): Boolean` method to `Group` that provides direct access to the filter.

**Comment by ncreep** [comment]
As I see it the Selector trait should be as general as possible, coupling it with a specific implementation/optimization kind of looks wrong to me.

So if some mechanism wants to optimize, the responsibility for it is on its side, not the Selector's, which should know nothing about it.

**Comment by djspiewak** [comment]
Actually, I think this is fairly nice.  The optimization was nearly hard-coded for element section anyway, and those semantics were spread around somewhat unnecessarily.  This change localizes the tangling quite a bit and makes it possible for us to optimize other sorts of selectors later simply by adding a case statement.  +1

The one change I'm going to make is `ElemSelector` should be `private[antixml]` and the implicit conversion should return an instance of `Selector[Elem]` to avoid leaking implementation details.

**Comment by josharnold52** [comment]
Agreed that the optimization is really only useful for Element selection.   But why should that restrict what the selector can return?    Couldn't you just as well define ElemSelector as something like:

```
/** A selector that selects an element by name. */
class ElemSelector[A](val elementName: String, mapping: (Elem) => A) extends Selector[A] {
  // not using a case class to allow inheritance
  private val pf: PartialFunction[Node, Elem] = {
    case e @ Elem(_, `elementName`, _, _, _) => mapping(e)
  }

  def apply(node: Node) = pf(node)
  def isDefinedAt(node: Node) = pf isDefinedAt node
}
```

**Pull request merged**
